enum ErrorCode {
    ERR_EMAIL_ADDRESS_TAKEN = 'ERR_EMAIL_ADDRESS_TAKEN',
    ERR_UNAUTHORIZED = 'ERR_UNAUTHORIZED',
    ERR_INVALID_FORM = 'ERR_INVALID_FORM',
    ERR_NOT_FOUND = 'ERR_NOT_FOUND',
    ERROR = 'ERROR'
}

export default ErrorCode;
